/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.itenas.oop.org.uashotel.swing.component;

import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author apple
 */
public class PanelCover extends javax.swing.JPanel {

    private final DecimalFormat df = new DecimalFormat("##0.###", DecimalFormatSymbols.getInstance(Locale.US));
    private ActionListener event;
    private MigLayout layout;
    private JLabel judul;
    private JLabel deskripsi;
    private JLabel deskripsi1;
    private ButtonOutLine button;
    private Boolean isLogin;
    
    public PanelCover() {
        initComponents();
        setOpaque(false);
        layout = new MigLayout("wrap, fill", "[center]", "push[]25[]10[]25[]push");
        setLayout(layout);
        init();
    }
    
    private void init() {
        judul = new JLabel ("Selamat Datang!");
        judul.setFont(new Font("sansserif", 1, 30));
        judul.setForeground(new Color(245,245,245));
        add(judul);
        deskripsi = new JLabel("Untuk terhubung dengan kami");
        deskripsi.setForeground(new Color(245, 245, 245));
        add(deskripsi);
        deskripsi1 = new JLabel("login dengan akunmu!");
        deskripsi1.setForeground(new Color(245, 245, 245));
        add(deskripsi1);
        button = new ButtonOutLine();
        button.setBackground(new Color(255, 255, 255));
        button.setForeground(new Color(255, 255, 255));
        button.setText("SIGN IN");
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.actionPerformed(ae);
            }
        });
        add(button, "w 60%, h 40");
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        GradientPaint gra = new GradientPaint (0, 0, new Color(173, 151, 79), 0, getHeight(), new Color(48, 45, 35));
        g2.setPaint(gra);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(grphcs);
    }
    
    public void addEvent(ActionListener event) {
        this.event = event;
    }

    public void registerLeft(double v) {
        v = Double.valueOf(df.format(v));
        login(false);
        layout.setComponentConstraints(judul, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(deskripsi, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(deskripsi1, "pad 0 -" + v + "% 0 0");

    }
    
    public void registerRight(double v) {
        v = Double.valueOf(df.format(v));
        login(false);
        layout.setComponentConstraints(judul, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(deskripsi, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(deskripsi1, "pad 0 -" + v + "% 0 0");
    }

    public void loginLeft(double v) {
        v = Double.valueOf(df.format(v));
        login(true);
        layout.setComponentConstraints(judul, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(deskripsi, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(deskripsi1, "pad 0 " + v + "% 0 " + v + "%");
    }

    public void loginRight(double v) {
        v = Double.valueOf(df.format(v));
        login(true);
        layout.setComponentConstraints(judul, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(deskripsi, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(deskripsi1, "pad 0 " + v + "% 0 " + v + "%");
    }

    private void login(Boolean l) {
       if (this.isLogin != l) {
            if (l) {
                judul.setText("Halo, Kitsune!");
                deskripsi.setText("Daftarkan dirimu");
                deskripsi1.setText("dan pesan kamar sekarang!");
                button.setText("SIGN UP");
            } else {
                judul.setText("Selamat Datang!");
                deskripsi.setText("Untuk terhubung dengan kami");
                deskripsi1.setText("login dengan akunmu!");
                button.setText("SIGN IN");
            }
            this.isLogin = l ;
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
